app:
  version: ${APP_VERSION:local}
  name: springlab-cesar-arico

server:
  port: 8080

spring:
  #Configuracion del datasource (MySQL local)
  datasource:
    url: jdbc:mysql://localhost:3306/spring_lab?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Configuracion de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  #Configuracion de Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

  #Configurar DevTools
  devtools:
    restart:
      enabled: true